services:
  - type: web
    name: ahmet-spotify-playlists
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
      - key: HOOK_SECRET
        sync: false
    autoDeploy: true